# Generated by Django 5.1.6 on 2025-02-08 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'وضعیت کاربر', 'verbose_name_plural': 'وضعیت کاربران'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'ویدئو ها', 'verbose_name_plural': 'ویدئو'},
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(default='', upload_to='videos/', verbose_name='عکس دوره'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.category', verbose_name='دسته ی مادر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(verbose_name='مدت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('published', 'منتشر شده'), ('draft', 'پیش نویس')], default='draft', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completion_status',
            field=models.CharField(choices=[('watched', 'Watched'), ('not_watched', 'Not Watched')], default='not_watched', max_length=11, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_watched',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تاریخ دیده شده'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.video', verbose_name='ویدئو'),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course', verbose_name='دوره ی'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='آدرس'),
        ),
    ]
