# Generated by Django 5.1.6 on 2025-02-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیفات'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'خرید', 'verbose_name_plural': 'خرید ها'},
        ),
    ]
