# Generated by Django 5.1.6 on 2025-02-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلانات'},
        ),
    ]
